import { HttpResponse } from "@angular/common/http";
import { Component, OnInit } from "@angular/core";
import { Router } from '@angular/router';
import { FarmResponseModel } from "@app/shared/models/farm-response.model";
import { Farm } from "@app/shared/models/farm.model";
import { FarmService } from "@app/shared/services/upr/farm.service";
import { BsModalRef, BsModalService } from "ngx-bootstrap/modal";
import { NGXLogger } from "ngx-logger";
import { ToastrTranslationService } from "@app/shared/services/toastr-translation.service";
import { IPagination } from "@app/shared/models/pagination.model";

@Component({
  selector: "app-farm-list",
  templateUrl: "./farm-list.component.html",
  styleUrls: ["./farm-list.component.css"],
})
export class FarmListComponent implements OnInit {
  farmList: Farm[] = [];
  modalRef: BsModalRef;
  pagination: IPagination;
  currentPage = 1;

  constructor(
    private _farmService: FarmService,
    private _modalService: BsModalService,
    private _logger: NGXLogger,
    private _toastrTranslated: ToastrTranslationService,
    private _router: Router
  ) {}

  ngOnInit() {
    this.getFarms();
  }
  
  onFarmCopy(farm: Farm) {
    let copyFarm = {...farm};
    copyFarm.id = null;
    copyFarm.name = farm.name + " [Copy]";
    this._farmService.createFarm(copyFarm).subscribe(
      (response) => {
        if (response.ok) {
          //this.farmList.push(copyFarm);
          this._toastrTranslated.showTranslatedToastr("Information_messages.Farm_copy_success","Common_labels.Success","toast-success");
          this.getFarms();
        }
      },
      (error) => {
        this._logger.error("Farm copy error:",error);
      }
    );
  }

  getFarms() {
    this._farmService.getFarms(this.currentPage).subscribe((response: HttpResponse<FarmResponseModel>) => {
      if (response.body && response.body.value) {
        const farms = response.body.value;
        this.pagination = JSON.parse(response.headers.get('x-pagination'));
        farms.forEach((farm) => {
          if(!(farm.name === "Autogenerated_ExternalDss_Farm")) {
            this._farmService.getAddressFromCoordinates(farm.location.y, farm.location.x).subscribe( (data) => farm.location.address = data);
          }      
        });
        this.farmList = farms;
        this.removeAutogeneratedFarmFromList();
      }
    });
  }

  openModal(template) {
    this.modalRef = this._modalService.show(template);
  }

  onDeleteFarm(farmId) {
    if (farmId) {
      this._farmService
        .deleteFarm(farmId)
        .subscribe((response: HttpResponse<any>) => {
          if (response.status === 204) {
            const index: number = this.farmList.findIndex(
              (item) => item.id === farmId
            );

            if (index !== -1) {
              this.farmList.splice(index, 1);
            }
            this.getFarms();
          }
        });
    } else {
      this.farmList.splice(this.farmList.length - 1, 1);
    }
    this.modalRef.hide();
    if(this.farmList.length < 2){
      this.getPreviousPage();
    }
  }

  goToAddModelDSS(farmId) {
    this._router.navigate(['/user/farm',farmId,'edit','dss','add']);
  }

  private removeAutogeneratedFarmFromList():void {
    for (let i = 0; i < this.farmList.length; i++) {
      if (this.farmList[i].name === "Autogenerated_ExternalDss_Farm") {
        this.farmList.splice(i--, 1);
      }
    }
  }

  getNextPage() {
    this.currentPage++;
    return this.getFarms();
  }

  hasNextPage() {
    if(this.pagination){
      return this.pagination.HasNext;
    }
  }

  getPreviousPage() {
    this.currentPage--;
    return this.getFarms();
  }

  hasPreviousPage() {
    if(this.pagination){
      return this.pagination.HasPrevious;
    }
  }

  hasMorePages() {
    if(this.pagination){
      if(this.pagination.TotalPages > 1) {
        return true;
      }
    }
    return false;
  }

}
